In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
diabetes_df=pd.read_csv('datasets/diabetes.csv')

In [3]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [4]:
diabetes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 54.1 KB

In [5]:
diabetes_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.677083,72.389323,29.089844,141.753906,32.434635,0.471876,33.240885,0.348958
std,3.369578,30.464161,12.106039,8.890820,89.100847,6.880498,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.050000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
diabetes_df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

diabetes_df[columns] = diabetes_df[columns].replace(0, np.nan)

In [8]:
diabetes_df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
(diabetes_df == 0).sum()

Pregnancies                 111
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [10]:
diabetes_df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure               float64
SkinThickness                 int64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [11]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

X = diabetes_df.drop("Outcome", axis=1)
y = diabetes_df["Outcome"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

processed_df = pd.DataFrame(X_scaled, columns=X.columns)
processed_df["Outcome"] = y

In [12]:
processed_df.to_csv("datasets/processed_dataset.csv", index=False)

In [13]:
heart_df = pd.read_csv("datasets/heart.csv")
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [14]:
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [15]:
heart_df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [16]:
heart_df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [17]:
heart_df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [18]:
from sklearn.preprocessing import StandardScaler

X = heart_df.drop("target", axis=1)
y = heart_df["target"]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

processed_heart = pd.DataFrame(X_scaled, columns=X.columns)

processed_heart["target"] = y

In [19]:
processed_heart.to_csv("datasets/processed_heart.csv", index=False)

In [20]:
kidney_df = pd.read_csv("datasets/kidney_disease.csv")

In [21]:
kidney_df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [22]:
kidney_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    str
 7   pc              335 non-null    str
 8   pcc             396 non-null    str
 9   ba              396 non-null    str
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    str
 17  wc              295 non-null    str
 18  rc              270 non-null    str
 19  htn             398 non-null    str
 20  dm              398 non-null    str
 21  cad             398 non-null    str
 22  appet           399 non-null    str
 23  pe              399 non-null    str
 24  ane             399 non-null    str
 25  classification  400 non-null    str
dtypes: float64(11), int64(1), str(14)
memory usage: 81.4 KB

In [23]:
kidney_df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [24]:
kidney_df.replace("?", np.nan, inplace=True)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [25]:
kidney_df.dtypes

id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                   str
pc                    str
pcc                   str
ba                    str
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv                   str
wc                    str
rc                    str
htn                   str
dm                    str
cad                   str
appet                 str
pe                    str
ane                   str
classification        str
dtype: object

In [26]:
numeric_columns = [
    "id", "age", "bp", "sg", "al", "su",
    "bgr", "bu", "sc", "sod", "pot", "hemo",
    "pcv", "wc", "rc"
]

for col in numeric_columns:
    kidney_df[col] = pd.to_numeric(kidney_df[col], errors="coerce")

In [27]:
for col in numeric_columns:
    kidney_df[col] = kidney_df[col].fillna(kidney_df[col].median())

In [28]:
categorical_columns = [
    "rbc", "pc", "pcc", "ba",
    "htn", "dm", "cad",
    "appet", "pe", "ane"
]

for col in categorical_columns:
    kidney_df[col] = kidney_df[col].fillna(kidney_df[col].mode()[0])

In [29]:
kidney_df["classification"] = kidney_df["classification"].replace({
    "ckd": 1,
    "ckd\t": 1,
    "notckd": 0
})

In [30]:
print(kidney_df["classification"].value_counts())
print(kidney_df["classification"].unique())

classification
1    250
0    150
Name: count, dtype: int64
[1 0]

In [31]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in categorical_columns:
    kidney_df[col] = encoder.fit_transform(kidney_df[col].astype(str))

In [32]:
print(kidney_df["classification"].value_counts())
print(kidney_df["classification"].unique())

classification
1    250
0    150
Name: count, dtype: int64
[1 0]

In [33]:
kidney_df.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [34]:
from sklearn.preprocessing import StandardScaler

X = kidney_df.drop("classification", axis=1)
y = kidney_df["classification"]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

processed_kidney = pd.DataFrame(X_scaled, columns=X.columns)
processed_kidney["classification"] = y

In [35]:
processed_kidney.to_csv("datasets/processed_kidney.csv", index=False)

In [36]:
#Train First XGBoost Model

In [37]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
import joblib

In [38]:
diabetes_dataset_df = pd.read_csv("datasets/processed_diabetes.csv")

In [39]:
diabetes_dataset_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639947,0.864625,-0.032180,0.665181,0.311604,0.169483,0.468492,1.425995,1
1,-0.844885,-1.204727,-0.528124,-0.010112,-0.440843,-0.848549,-0.365061,-0.190672,0
2,1.233880,2.014265,-0.693438,0.327535,0.311604,-1.328478,0.604397,-0.105584,1
3,-0.844885,-1.073339,-0.528124,-0.685405,-0.536303,-0.630399,-0.920763,-1.041549,0
4,-1.141852,0.503310,-2.677212,0.665181,0.294758,1.551096,5.484909,-0.020496,1

In [40]:
X_diabetes = diabetes_dataset_df.drop("Outcome", axis=1)
y_diabetes = diabetes_dataset_df["Outcome"]

In [41]:
X_train_diabetes, X_test_diabetes, y_train_diabetes, y_test_diabetes = train_test_split(
    X_diabetes,
    y_diabetes,
    test_size=0.2,
    random_state=42
)

In [42]:
diabetes_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

In [43]:
diabetes_model.fit(X_train_diabetes, y_train_diabetes)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [44]:
predictions = diabetes_model.predict(X_test_diabetes)
probabilities = diabetes_model.predict_proba(X_test_diabetes)[:, 1]

In [45]:
accuracy = accuracy_score(y_test_diabetes, predictions)
precision = precision_score(y_test_diabetes, predictions)
recall = recall_score(y_test_diabetes, predictions)
f1 = f1_score(y_test_diabetes, predictions)
roc_auc = roc_auc_score(y_test_diabetes, probabilities)

print(f"Accuracy : {accuracy * 100:.2f}%")
print(f"Precision: {precision * 100:.2f}%")
print(f"Recall   : {recall * 100:.2f}%")
print(f"F1 Score : {f1 * 100:.2f}%")
print(f"ROC-AUC  : {roc_auc * 100:.2f}%")

Accuracy : 85.06%
Precision: 79.63%
Recall   : 78.18%
F1 Score : 78.90%
ROC-AUC  : 92.95%

In [46]:
joblib.dump(diabetes_model, "backend/ml/models/xgboost_diabetes_model.pkl")

['backend/ml/models/xgboost_diabetes_model.pkl']

In [47]:
print(X.columns.tolist())
print(len(X.columns))

['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane']
25

In [48]:
print("Diabetes model saved successfully!")

Diabetes model saved successfully!

In [49]:
# training heart

In [50]:
heart_dataset_df = pd.read_csv("datasets/processed_heart.csv")

In [51]:
heart_dataset_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0.952197,0.681005,1.973123,0.763956,-0.256334,2.394438,-1.005832,0.015443,-0.696631,1.087338,-2.274579,-0.714429,-2.148873,1
1,-1.915313,0.681005,1.002577,-0.092738,0.072199,-0.417635,0.898962,1.633471,-0.696631,2.122573,-2.274579,-0.714429,-0.512922,1
2,-1.474158,-1.468418,0.032031,-0.092738,-0.816773,-0.417635,-1.005832,0.977514,-0.696631,0.310912,0.976352,-0.714429,-0.512922,1
3,0.180175,0.681005,0.032031,-0.663867,-0.198357,-0.417635,0.898962,1.239897,-0.696631,-0.206705,0.976352,-0.714429,-0.512922,1
4,0.290464,-1.468418,-0.938515,-0.663867,2.082050,-0.417635,0.898962,0.583939,1.435481,-0.379244,0.976352,-0.714429,-0.512922,1

In [52]:
heart_dataset_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        303 non-null    float64
 12  thal      303 non-null    float64
 13  target    303 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 33.3 KB

In [53]:
heart_dataset_df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [54]:
X_heart = heart_dataset_df.drop("target", axis=1)
y_heart = heart_dataset_df["target"]

In [55]:
X_train_heart, X_test_heart, y_train_heart, y_test_heart = train_test_split(
    X_heart,
    y_heart,
    test_size=0.2,
    random_state=42
)

In [56]:
heart_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

In [57]:
heart_model.fit(X_train_heart, y_train_heart)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [58]:
predictions = heart_model.predict(X_test_heart)
probabilities = heart_model.predict_proba(X_test_heart)[:, 1]

In [59]:
accuracy = accuracy_score(y_test_heart, predictions)
precision = precision_score(y_test_heart, predictions)
recall = recall_score(y_test_heart, predictions)
f1 = f1_score(y_test_heart, predictions)
roc_auc = roc_auc_score(y_test_heart, probabilities)

print(f"Accuracy : {accuracy * 100:.2f}%")
print(f"Precision: {precision * 100:.2f}%")
print(f"Recall   : {recall * 100:.2f}%")
print(f"F1 Score : {f1 * 100:.2f}%")
print(f"ROC-AUC  : {roc_auc * 100:.2f}%")

Accuracy : 81.97%
Precision: 86.21%
Recall   : 78.12%
F1 Score : 81.97%
ROC-AUC  : 90.73%

In [60]:
joblib.dump(heart_model, "backend/ml/models/xgboost_heart_model.pkl")

['backend/ml/models/xgboost_heart_model.pkl']

In [61]:
print("Heart disease model saved successfully!")

Heart disease model saved successfully!

In [62]:
# kidney

In [63]:
kidney_dataset_df = pd.read_csv("datasets/processed_kidney.csv")

In [64]:
kidney_dataset_df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,-1.727726,-0.210031,0.254214,0.421486,0.076249,-0.380269,0.36489,0.484322,-0.342518,-0.241249,...,0.603224,-0.197314,0.550044,1.311903,1.209416,-0.276686,-0.507801,-0.484322,-0.420084,1
1,-1.719066,-2.627234,-1.972476,0.421486,2.363728,-0.380269,0.36489,0.484322,-0.342518,-0.241249,...,-0.132789,-0.909782,0.074073,-0.762252,-0.518321,-0.276686,-0.507801,-0.484322,-0.420084,1
2,-1.710406,0.615355,0.254214,-1.421074,0.838742,2.507853,0.36489,0.484322,-0.342518,-0.241249,...,-0.991470,-0.316059,0.074073,-0.762252,1.209416,-0.276686,1.969276,-0.484322,2.380476,1
3,-1.701745,-0.210031,-0.488016,-2.342354,2.363728,-0.380269,0.36489,-2.064742,2.919556,-0.241249,...,-0.868801,-0.632711,-0.996862,1.311903,-0.518321,-0.276686,1.969276,2.064742,2.380476,1
4,-1.693085,-0.033163,0.254214,-1.421074,0.838742,-0.380269,0.36489,0.484322,-0.342518,-0.241249,...,-0.500795,-0.395222,-0.163913,-0.762252,-0.518321,-0.276686,-0.507801,-0.484322,-0.420084,1

In [65]:
kidney_dataset_df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,-1.727726,-0.210031,0.254214,0.421486,0.076249,-0.380269,0.36489,0.484322,-0.342518,-0.241249,...,0.603224,-0.197314,0.550044,1.311903,1.209416,-0.276686,-0.507801,-0.484322,-0.420084,1
1,-1.719066,-2.627234,-1.972476,0.421486,2.363728,-0.380269,0.36489,0.484322,-0.342518,-0.241249,...,-0.132789,-0.909782,0.074073,-0.762252,-0.518321,-0.276686,-0.507801,-0.484322,-0.420084,1
2,-1.710406,0.615355,0.254214,-1.421074,0.838742,2.507853,0.36489,0.484322,-0.342518,-0.241249,...,-0.991470,-0.316059,0.074073,-0.762252,1.209416,-0.276686,1.969276,-0.484322,2.380476,1
3,-1.701745,-0.210031,-0.488016,-2.342354,2.363728,-0.380269,0.36489,-2.064742,2.919556,-0.241249,...,-0.868801,-0.632711,-0.996862,1.311903,-0.518321,-0.276686,1.969276,2.064742,2.380476,1
4,-1.693085,-0.033163,0.254214,-1.421074,0.838742,-0.380269,0.36489,0.484322,-0.342518,-0.241249,...,-0.500795,-0.395222,-0.163913,-0.762252,-0.518321,-0.276686,-0.507801,-0.484322,-0.420084,1

In [66]:
kidney_dataset_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    float64
 1   age             400 non-null    float64
 2   bp              400 non-null    float64
 3   sg              400 non-null    float64
 4   al              400 non-null    float64
 5   su              400 non-null    float64
 6   rbc             400 non-null    float64
 7   pc              400 non-null    float64
 8   pcc             400 non-null    float64
 9   ba              400 non-null    float64
 10  bgr             400 non-null    float64
 11  bu              400 non-null    float64
 12  sc              400 non-null    float64
 13  sod             400 non-null    float64
 14  pot             400 non-null    float64
 15  hemo            400 non-null    float64
 16  pcv             400 non-null    float64
 17  wc              400 non-null    float64
 18  rc              400 non-null    float64
 19  htn             400 non-null    float64
 20  dm              400 non-null    float64
 21  cad             400 non-null    float64
 22  appet           400 non-null    float64
 23  pe              400 non-null    float64
 24  ane             400 non-null    float64
 25  classification  400 non-null    int64
dtypes: float64(25), int64(1)
memory usage: 81.4 KB

In [67]:
kidney_dataset_df.columns
print(kidney_df["classification"].value_counts())
print(kidney_df["classification"].unique())

classification
1    250
0    150
Name: count, dtype: int64
[1 0]

In [68]:
X_kidney = kidney_dataset_df.drop("classification", axis=1)
y_kidney = kidney_dataset_df["classification"]

In [69]:
X_train_kidney, X_test_kidney, y_train_kidney, y_test_kidney = train_test_split(
    X_kidney,
    y_kidney,
    test_size=0.2,
    random_state=42
)

In [70]:
kidney_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

In [71]:
kidney_model.fit(X_train_kidney, y_train_kidney)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [72]:
predictions = kidney_model.predict(X_test_kidney)
probabilities = kidney_model.predict_proba(X_test_kidney)[:, 1]
print(y_train_kidney.unique())
print(y_test_kidney.unique())
print(kidney_model.classes_)

[1 0]
[1 0]
[0 1]

In [73]:
accuracy = accuracy_score(y_test_kidney, predictions)
precision = precision_score(y_test_kidney, predictions)
recall = recall_score(y_test_kidney, predictions)
f1 = f1_score(y_test_kidney, predictions)
roc_auc = roc_auc_score(y_test_kidney, probabilities)

print(f"Accuracy : {accuracy * 100:.2f}%")
print(f"Precision: {precision * 100:.2f}%")
print(f"Recall   : {recall * 100:.2f}%")
print(f"F1 Score : {f1 * 100:.2f}%")
print(f"ROC-AUC  : {roc_auc * 100:.2f}%")

joblib.dump(kidney_model, "backend/ml/models/xgboost_kidney_model.pkl")

Accuracy : 100.00%
Precision: 100.00%
Recall   : 100.00%
F1 Score : 100.00%
ROC-AUC  : 100.00%

['backend/ml/models/xgboost_kidney_model.pkl']

In [74]:
print("Kidney disease model saved successfully!")

Kidney disease model saved successfully!

In [75]:
import joblib

model = joblib.load("backend/ml/models/xgboost_diabetes_model.pkl")
print("Model loaded successfully!")

Model loaded successfully!

In [76]:
import os

print(os.getcwd())

D:\Medical_Intelligence_Ai\medintel-AI

In [77]:
import os

print(os.listdir())

['.git', '.gitignore', '.ipynb_checkpoints', '.python-version', '.venv', 'backend', 'datasets', 'frontend', 'jupyter_notebook.ipynb', 'main.py', 'pyproject.toml', 'README.md', 'requirements.txt', 'uv.lock']

In [78]:
import os

print(os.listdir("backend/ml/models"))

['ckd_model.pkl', 'diabetes_model.pkl', 'heart_model.pkl', 'preprocessors', 'xgboost_diabetes_model.pkl', 'xgboost_heart_model.pkl', 'xgboost_kidney_model.pkl']

In [79]:
import joblib

model = joblib.load("backend/ml/models/xgboost_diabetes_model.pkl")
print("Model loaded successfully!")

Model loaded successfully!

In [80]:
import os

print(os.listdir("backend/ml/models"))

['ckd_model.pkl', 'diabetes_model.pkl', 'heart_model.pkl', 'preprocessors', 'xgboost_diabetes_model.pkl', 'xgboost_heart_model.pkl', 'xgboost_kidney_model.pkl']

In [81]:
import joblib

model = joblib.load("backend/ml/models/xgboost_diabetes_model.pkl")
print("Model loaded successfully!")

Model loaded successfully!

In [82]:
import os

print(os.listdir("backend/ml/models"))

['ckd_model.pkl', 'diabetes_model.pkl', 'heart_model.pkl', 'preprocessors', 'xgboost_diabetes_model.pkl', 'xgboost_heart_model.pkl', 'xgboost_kidney_model.pkl']

In [83]:
from backend.ml.predict import predict_diabetes

print(diabetes_model.n_features_in_)

8

In [84]:
print(diabetes_dataset_df.head())

   Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.639947  0.864625      -0.032180       0.665181  0.311604  0.169483
1    -0.844885 -1.204727      -0.528124      -0.010112 -0.440843 -0.848549
2     1.233880  2.014265      -0.693438       0.327535  0.311604 -1.328478
3    -0.844885 -1.073339      -0.528124      -0.685405 -0.536303 -0.630399
4    -1.141852  0.503310      -2.677212       0.665181  0.294758  1.551096

   DiabetesPedigreeFunction       Age  Outcome
0                  0.468492  1.425995        1
1                 -0.365061 -0.190672        0
2                  0.604397 -0.105584        1
3                 -0.920763 -1.041549        0
4                  5.484909 -0.020496        1

In [85]:
print(heart_dataset_df.head())

        age       sex        cp  trestbps      chol       fbs   restecg  \
0  0.952197  0.681005  1.973123  0.763956 -0.256334  2.394438 -1.005832
1 -1.915313  0.681005  1.002577 -0.092738  0.072199 -0.417635  0.898962
2 -1.474158 -1.468418  0.032031 -0.092738 -0.816773 -0.417635 -1.005832
3  0.180175  0.681005  0.032031 -0.663867 -0.198357 -0.417635  0.898962
4  0.290464 -1.468418 -0.938515 -0.663867  2.082050 -0.417635  0.898962

    thalach     exang   oldpeak     slope        ca      thal  target
0  0.015443 -0.696631  1.087338 -2.274579 -0.714429 -2.148873       1
1  1.633471 -0.696631  2.122573 -2.274579 -0.714429 -0.512922       1
2  0.977514 -0.696631  0.310912  0.976352 -0.714429 -0.512922       1
3  1.239897 -0.696631 -0.206705  0.976352 -0.714429 -0.512922       1
4  0.583939  1.435481 -0.379244  0.976352 -0.714429 -0.512922       1

In [86]:
print(kidney_dataset_df.head())

         id       age        bp        sg        al        su      rbc  \
0 -1.727726 -0.210031  0.254214  0.421486  0.076249 -0.380269  0.36489
1 -1.719066 -2.627234 -1.972476  0.421486  2.363728 -0.380269  0.36489
2 -1.710406  0.615355  0.254214 -1.421074  0.838742  2.507853  0.36489
3 -1.701745 -0.210031 -0.488016 -2.342354  2.363728 -0.380269  0.36489
4 -1.693085 -0.033163  0.254214 -1.421074  0.838742 -0.380269  0.36489

         pc       pcc        ba  ...       pcv        wc        rc       htn  \
0  0.484322 -0.342518 -0.241249  ...  0.603224 -0.197314  0.550044  1.311903
1  0.484322 -0.342518 -0.241249  ... -0.132789 -0.909782  0.074073 -0.762252
2  0.484322 -0.342518 -0.241249  ... -0.991470 -0.316059  0.074073 -0.762252
3 -2.064742  2.919556 -0.241249  ... -0.868801 -0.632711 -0.996862  1.311903
4  0.484322 -0.342518 -0.241249  ... -0.500795 -0.395222 -0.163913 -0.762252

         dm       cad     appet        pe       ane  classification
0  1.209416 -0.276686 -0.507801 -0.484322 -0.420084               1
1 -0.518321 -0.276686 -0.507801 -0.484322 -0.420084               1
2  1.209416 -0.276686  1.969276 -0.484322  2.380476               1
3 -0.518321 -0.276686  1.969276  2.064742  2.380476               1
4 -0.518321 -0.276686 -0.507801 -0.484322 -0.420084               1

[5 rows x 26 columns]

In [87]:
print(X_diabetes.columns.tolist())
print(len(X_diabetes.columns))

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
8

In [88]:
print(X_heart.columns.tolist())
print(len(X_heart.columns))

print(X_kidney.columns.tolist())
print(len(X_kidney.columns))

['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
13
['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane']
25

In [89]:
print(X_kidney.columns.tolist())
print(len(X_kidney.columns))

['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane']
25

In [90]:
from backend.ml.predict import predict_diabetes

sample = [6, 148, 72, 35, 0, 33.6, 0.627, 50]

print(predict_diabetes(sample))

{'prediction': 'Diabetes', 'confidence': 0.87, 'risk': 'Medium', 'probabilities': {'No Diabetes': 0.13, 'Diabetes': 0.87}}

In [91]:
from backend.ml.predict import predict_kidney

sample = [
    1, 48, 80, 1.02, 1, 0, 1, 1, 0, 0,
    121, 36, 1.2, 135, 4.5, 15.4, 44,
    7800, 5.2, 1, 1, 0, 1, 0, 0
]

print(predict_kidney(sample))

{'prediction': 'No Kidney Disease', 'confidence': 0.99, 'risk': 'Low', 'probabilities': {'No Kidney Disease': 0.99, 'Kidney Disease': 0.01}}

In [92]:
from backend.ml.predict import predict_heart

sample = [63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1]

print(predict_heart(sample))

{'prediction': 'No Heart Disease', 'confidence': 0.58, 'risk': 'Low', 'probabilities': {'No Heart Disease': 0.58, 'Heart Disease': 0.42}}

In [93]:
import pandas as pd

print(pd.read_csv("datasets/processed_diabetes.csv").columns.tolist())
print(pd.read_csv("datasets/processed_heart.csv").columns.tolist())
print(pd.read_csv("datasets/processed_kidney.csv").columns.tolist())

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']
['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']

In [94]:
from backend.ml.feature_engineering import (
    load_dataset,
    prepare_features
)

df = load_dataset("datasets/processed_diabetes.csv")

X, y, scaler = prepare_features(df, "Outcome")

print(X.shape)
print(y.shape)

(768, 8)
(768,)

In [95]:
from backend.ml.predict import predict_diabetes

sample = [
    6,
    148,
    72,
    35,
    0,
    33.6,
    0.627,
    50
]

print(predict_diabetes(sample))

{'prediction': 'Diabetes', 'confidence': 0.87, 'risk': 'Medium', 'probabilities': {'No Diabetes': 0.13, 'Diabetes': 0.87}}

In [96]:
from backend.ml.predict import predict_heart

sample = [
    63,
    1,
    3,
    145,
    233,
    1,
    0,
    150,
    0,
    2.3,
    0,
    0,
    1
]

print(predict_heart(sample))

{'prediction': 'No Heart Disease', 'confidence': 0.58, 'risk': 'Low', 'probabilities': {'No Heart Disease': 0.58, 'Heart Disease': 0.42}}

In [97]:
from backend.ml.predict import predict_kidney

sample = [
    1,      # id
    48,     # age
    80,     # bp
    1.020,  # sg
    1,      # al
    0,      # su
    1,      # rbc
    1,      # pc
    0,      # pcc
    0,      # ba
    121,    # bgr
    36,     # bu
    1.2,    # sc
    135,    # sod
    4.5,    # pot
    15.4,   # hemo
    44,     # pcv
    7800,   # wc
    5.2,    # rc
    1,      # htn
    1,      # dm
    0,      # cad
    1,      # appet
    0,      # pe
    0       # ane
]

print(predict_kidney(sample))

{'prediction': 'No Kidney Disease', 'confidence': 0.99, 'risk': 'Low', 'probabilities': {'No Kidney Disease': 0.99, 'Kidney Disease': 0.01}}

In [98]:
print("Kidney model features:", kidney_model.n_features_in_)

Kidney model features: 25

In [99]:
import joblib

defaults = joblib.load(
    "backend/ml/models/preprocessors/diabetes_defaults.pkl"
)

print(defaults)

{'Pregnancies': -0.2509521280020695, 'Glucose': -0.1536274492976735, 'BloodPressure': -0.0321803544595584, 'SkinThickness': -0.1226606774423956, 'Insulin': -0.4408430295055168, 'BMI': -0.05593869608349204, 'DiabetesPedigreeFunction': -0.3001282260084456, 'Age': -0.3608474114058894}

In [100]:
import pandas as pd

df = pd.read_csv("datasets/processed_diabetes.csv")

print(df.head())
print()
print(df.describe())

   Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.639947  0.864625      -0.032180       0.665181  0.311604  0.169483
1    -0.844885 -1.204727      -0.528124      -0.010112 -0.440843 -0.848549
2     1.233880  2.014265      -0.693438       0.327535  0.311604 -1.328478
3    -0.844885 -1.073339      -0.528124      -0.685405 -0.536303 -0.630399
4    -1.141852  0.503310      -2.677212       0.665181  0.294758  1.551096

   DiabetesPedigreeFunction       Age  Outcome
0                  0.468492  1.425995        1
1                 -0.365061 -0.190672        0
2                  0.604397 -0.105584        1
3                 -0.920763 -1.041549        0
4                  5.484909 -0.020496        1

        Pregnancies       Glucose  BloodPressure  SkinThickness       Insulin  \
count  7.680000e+02  7.680000e+02   7.680000e+02   7.680000e+02  7.680000e+02
mean  -5.551115e-17  1.503427e-16  -3.804827e-16   2.312965e-18  1.156482e-18
std    1.000652e+00  1.000652e+00   1.000652e+00   1.000652e+00  1.000652e+00
min   -1.141852e+00 -2.551447e+00  -3.999727e+00  -2.486187e+00 -1.434747e+00
25%   -8.448851e-01 -7.202356e-01  -6.934382e-01  -4.603073e-01 -4.408430e-01
50%   -2.509521e-01 -1.536274e-01  -3.218035e-02  -1.226607e-01 -4.408430e-01
75%    6.399473e-01  6.100618e-01   6.290775e-01   3.275348e-01  3.116039e-01
max    3.906578e+00  2.539814e+00   4.100681e+00   7.868309e+00  7.909072e+00

                BMI  DiabetesPedigreeFunction           Age     Outcome
count  7.680000e+02              7.680000e+02  7.680000e+02  768.000000
mean   1.156482e-16              2.451743e-16  1.838807e-16    0.348958
std    1.000652e+00              1.000652e+00  1.000652e+00    0.476951
min   -2.070186e+00             -1.189553e+00 -1.041549e+00    0.000000
25%   -7.176590e-01             -6.889685e-01 -7.862862e-01    0.000000
50%   -5.593870e-02             -3.001282e-01 -3.608474e-01    0.000000
75%    6.057816e-01              4.662269e-01  6.602056e-01    1.000000
max    5.041489e+00              5.883565e+00  4.063716e+00    1.000000

In [101]:
import pandas as pd

df = pd.read_csv("datasets/clean_diabetes_dataset.csv")

print(df.head())
print(df.info())
print(df.isnull().sum())

    Age Gender  Pregnancies  Glucose  HbA1c   BMI  BloodPressure  Insulin  \
0  50.0      0          6.0    148.0    5.8  33.6           72.0    169.5
1  31.0      0          1.0     85.0    5.8  26.6           66.0    102.5
2  32.0      0          8.0    183.0    5.8  23.3           64.0    169.5
3  21.0      0          1.0     89.0    5.8  28.1           66.0     94.0
4  33.0      0          0.0    137.0    5.8  43.1           40.0    168.0

  Hypertension  Smoking FamilyHistory  HeartDisease Outcome
0            0        8         0.627           0.0       1
1            0        8         0.351           0.0       0
2            0        8         0.672           0.0       1
3            0        8         0.167           0.0       0
4            0        8         2.288           0.0       1
<class 'pandas.DataFrame'>
RangeIndex: 99914 entries, 0 to 99913
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            99914 non-null  float64
 1   Gender         99914 non-null  str
 2   Pregnancies    99914 non-null  float64
 3   Glucose        99914 non-null  float64
 4   HbA1c          99914 non-null  float64
 5   BMI            99914 non-null  float64
 6   BloodPressure  99914 non-null  float64
 7   Insulin        99914 non-null  float64
 8   Hypertension   99914 non-null  object
 9   Smoking        99914 non-null  int64
 10  FamilyHistory  99914 non-null  str
 11  HeartDisease   99914 non-null  float64
 12  Outcome        99914 non-null  object
dtypes: float64(8), int64(1), object(2), str(2)
memory usage: 9.9+ MB
None
Age              0
Gender           0
Pregnancies      0
Glucose          0
HbA1c            0
BMI              0
BloodPressure    0
Insulin          0
Hypertension     0
Smoking          0
FamilyHistory    0
HeartDisease     0
Outcome          0
dtype: int64

C:\Users\Manasi\AppData\Local\Temp\ipykernel_13620\4160927144.py:3: DtypeWarning: Columns (0: Hypertension, 1: Outcome) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("datasets/clean_diabetes_dataset.csv")

In [103]:
import pandas as pd

df = pd.read_csv("datasets/clean_diabetes_dataset.csv")

print(df.info())
print(df.isnull().sum())
print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 99914 entries, 0 to 99913
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            99914 non-null  float64
 1   Gender         99914 non-null  str
 2   Pregnancies    99914 non-null  float64
 3   Glucose        99914 non-null  float64
 4   HbA1c          99914 non-null  float64
 5   BMI            99914 non-null  float64
 6   BloodPressure  99914 non-null  float64
 7   Insulin        99914 non-null  float64
 8   Hypertension   99914 non-null  object
 9   Smoking        99914 non-null  int64
 10  FamilyHistory  99914 non-null  str
 11  HeartDisease   99914 non-null  float64
 12  Outcome        99914 non-null  object
dtypes: float64(8), int64(1), object(2), str(2)
memory usage: 9.9+ MB
None
Age              0
Gender           0
Pregnancies      0
Glucose          0
HbA1c            0
BMI              0
BloodPressure    0
Insulin          0
Hypertension     0
Smoking          0
FamilyHistory    0
HeartDisease     0
Outcome          0
dtype: int64
    Age Gender  Pregnancies  Glucose  HbA1c   BMI  BloodPressure  Insulin  \
0  50.0      0          6.0    148.0    5.8  33.6           72.0    169.5
1  31.0      0          1.0     85.0    5.8  26.6           66.0    102.5
2  32.0      0          8.0    183.0    5.8  23.3           64.0    169.5
3  21.0      0          1.0     89.0    5.8  28.1           66.0     94.0
4  33.0      0          0.0    137.0    5.8  43.1           40.0    168.0

  Hypertension  Smoking FamilyHistory  HeartDisease Outcome
0            0        8         0.627           0.0       1
1            0        8         0.351           0.0       0
2            0        8         0.672           0.0       1
3            0        8         0.167           0.0       0
4            0        8         2.288           0.0       1

C:\Users\Manasi\AppData\Local\Temp\ipykernel_13620\574842317.py:3: DtypeWarning: Columns (0: Hypertension, 1: Outcome) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("datasets/clean_diabetes_dataset.csv")

In [104]:
import pandas as pd

df = pd.read_csv("datasets/clean_diabetes_dataset.csv")

print(df.info())
print(df.isnull().sum())
print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 99914 entries, 0 to 99913
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            99914 non-null  float64
 1   Gender         99914 non-null  str
 2   Pregnancies    99914 non-null  float64
 3   Glucose        99914 non-null  float64
 4   HbA1c          99914 non-null  float64
 5   BMI            99914 non-null  float64
 6   BloodPressure  99914 non-null  float64
 7   Insulin        99914 non-null  float64
 8   Hypertension   99914 non-null  object
 9   Smoking        99914 non-null  int64
 10  FamilyHistory  99914 non-null  str
 11  HeartDisease   99914 non-null  float64
 12  Outcome        99914 non-null  object
dtypes: float64(8), int64(1), object(2), str(2)
memory usage: 9.9+ MB
None
Age              0
Gender           0
Pregnancies      0
Glucose          0
HbA1c            0
BMI              0
BloodPressure    0
Insulin          0
Hypertension     0
Smoking          0
FamilyHistory    0
HeartDisease     0
Outcome          0
dtype: int64
    Age Gender  Pregnancies  Glucose  HbA1c   BMI  BloodPressure  Insulin  \
0  50.0      0          6.0    148.0    5.8  33.6           72.0    169.5
1  31.0      0          1.0     85.0    5.8  26.6           66.0    102.5
2  32.0      0          8.0    183.0    5.8  23.3           64.0    169.5
3  21.0      0          1.0     89.0    5.8  28.1           66.0     94.0
4  33.0      0          0.0    137.0    5.8  43.1           40.0    168.0

  Hypertension  Smoking FamilyHistory  HeartDisease Outcome
0            0        8         0.627           0.0       1
1            0        8         0.351           0.0       0
2            0        8         0.672           0.0       1
3            0        8         0.167           0.0       0
4            0        8         2.288           0.0       1

C:\Users\Manasi\AppData\Local\Temp\ipykernel_13620\574842317.py:3: DtypeWarning: Columns (0: Hypertension, 1: Outcome) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("datasets/clean_diabetes_dataset.csv")

In [105]:
import pandas as pd

df = pd.read_csv(
    "datasets/combined_heart_dataset.csv",
    low_memory=False
)

print(df.head())

print("\n")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nUnique values")

for col in df.columns:
    if df[col].dtype == "object":
        print("\n", col)
        print(df[col].unique()[:20])

    Age  Sex  Height  Weight    BMI  SystolicBP  DiastolicBP  \
0  39.0  1.0     NaN     NaN  26.97       106.0         70.0
1  46.0  0.0     NaN     NaN  28.73       121.0         81.0
2  48.0  1.0     NaN     NaN  25.34       127.5         80.0
3  61.0  0.0     NaN     NaN  28.58       150.0         95.0
4  46.0  0.0     NaN     NaN  23.10       130.0         84.0

   TotalCholesterol  Glucose  Smoking  Diabetes  Hypertension  Alcohol  \
0             195.0     77.0      0.0       0.0           0.0      NaN
1             250.0     76.0      0.0       0.0           0.0      NaN
2             245.0     70.0      1.0       0.0           0.0      NaN
3             225.0    103.0      1.0       0.0           1.0      NaN
4             285.0     85.0      1.0       0.0           0.0      NaN

   PhysicalActivity  HeartRate  Platelets  SerumCreatinine  SerumSodium  CPK  \
0               NaN       80.0        NaN              NaN          NaN  NaN
1               NaN       95.0        NaN              NaN          NaN  NaN
2               NaN       75.0        NaN              NaN          NaN  NaN
3               NaN       65.0        NaN              NaN          NaN  NaN
4               NaN       85.0        NaN              NaN          NaN  NaN

   Target
0     0.0
1     0.0
2     0.0
3     1.0
4     0.0


<class 'pandas.DataFrame'>
RangeIndex: 74537 entries, 0 to 74536
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               4537 non-null   float64
 1   Sex               4537 non-null   float64
 2   Height            0 non-null      float64
 3   Weight            0 non-null      float64
 4   BMI               4219 non-null   float64
 5   SystolicBP        4238 non-null   float64
 6   DiastolicBP       4238 non-null   float64
 7   TotalCholesterol  4188 non-null   float64
 8   Glucose           3850 non-null   float64
 9   Smoking           4238 non-null   float64
 10  Diabetes          4537 non-null   float64
 11  Hypertension      4537 non-null   float64
 12  Alcohol           0 non-null      float64
 13  PhysicalActivity  0 non-null      float64
 14  HeartRate         4237 non-null   float64
 15  Platelets         299 non-null    float64
 16  SerumCreatinine   299 non-null    float64
 17  SerumSodium       299 non-null    float64
 18  CPK               299 non-null    float64
 19  Target            4537 non-null   float64
dtypes: float64(20)
memory usage: 11.4 MB
None

Missing Values
Age                 70000
Sex                 70000
Height              74537
Weight              74537
BMI                 70318
SystolicBP          70299
DiastolicBP         70299
TotalCholesterol    70349
Glucose             70687
Smoking             70299
Diabetes            70000
Hypertension        70000
Alcohol             74537
PhysicalActivity    74537
HeartRate           70300
Platelets           74238
SerumCreatinine     74238
SerumSodium         74238
CPK                 74238
Target              70000
dtype: int64

Unique values

In [106]:
    Age  Sex  Height  Weight    BMI  SystolicBP  DiastolicBP  \
0  39.0  1.0     NaN     NaN  26.97       106.0         70.0   
1  46.0  0.0     NaN     NaN  28.73       121.0         81.0   
2  48.0  1.0     NaN     NaN  25.34       127.5         80.0   
3  61.0  0.0     NaN     NaN  28.58       150.0         95.0   
4  46.0  0.0     NaN     NaN  23.10       130.0         84.0   

   TotalCholesterol  Glucose  Smoking  Diabetes  Hypertension  Alcohol  \
0             195.0     77.0      0.0       0.0           0.0      NaN   
1             250.0     76.0      0.0       0.0           0.0      NaN   
2             245.0     70.0      1.0       0.0           0.0      NaN   
3             225.0    103.0      1.0       0.0           1.0      NaN   
4             285.0     85.0      1.0       0.0           0.0      NaN   

   PhysicalActivity  HeartRate  Platelets  SerumCreatinine  SerumSodium  CPK  \
0               NaN       80.0        NaN              NaN          NaN  NaN   
1               NaN       95.0        NaN              NaN          NaN  NaN   
2               NaN       75.0        NaN              NaN          NaN  NaN   
3               NaN       65.0        NaN              NaN          NaN  NaN   
4               NaN       85.0        NaN              NaN          NaN  NaN   

   Target  
0     0.0  
1     0.0  
2     0.0  
3     1.0  
4     0.0  


<class 'pandas.DataFrame'>
RangeIndex: 74537 entries, 0 to 74536
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               4537 non-null   float64
 1   Sex               4537 non-null   float64
 2   Height            0 non-null      float64
 3   Weight            0 non-null      float64
 4   BMI               4219 non-null   float64
 5   SystolicBP        4238 non-null   float64
 6   DiastolicBP       4238 non-null   float64
 7   TotalCholesterol  4188 non-null   float64
 8   Glucose           3850 non-null   float64
 9   Smoking           4238 non-null   float64
 10  Diabetes          4537 non-null   float64
 11  Hypertension      4537 non-null   float64
 12  Alcohol           0 non-null      float64
 13  PhysicalActivity  0 non-null      float64
 14  HeartRate         4237 non-null   float64
 15  Platelets         299 non-null    float64
 16  SerumCreatinine   299 non-null    float64
 17  SerumSodium       299 non-null    float64
 18  CPK               299 non-null    float64
 19  Target            4537 non-null   float64
dtypes: float64(20)
memory usage: 11.4 MB
None

Missing Values
Age                 70000
Sex                 70000
Height              74537
Weight              74537
BMI                 70318
SystolicBP          70299
DiastolicBP         70299
TotalCholesterol    70349
Glucose             70687
Smoking             70299
Diabetes            70000
Hypertension        70000
Alcohol             74537
PhysicalActivity    74537
HeartRate           70300
Platelets           74238
SerumCreatinine     74238
SerumSodium         74238
CPK                 74238
Target              70000
dtype: int64

Unique values

IndentationError: unexpected indent (630445952.py, line 1)

In [109]:
import pandas as pd

df = pd.read_csv(
    "datasets/combined_heart_dataset.csv",
    low_memory=False
)

print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 74537 entries, 0 to 74536
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               74537 non-null  float64
 1   Sex               74537 non-null  int64
 2   Height            70000 non-null  float64
 3   Weight            70000 non-null  float64
 4   BMI               4219 non-null   float64
 5   SystolicBP        74238 non-null  float64
 6   DiastolicBP       74238 non-null  float64
 7   TotalCholesterol  74188 non-null  float64
 8   Glucose           73850 non-null  float64
 9   Smoking           74238 non-null  float64
 10  Diabetes          4537 non-null   float64
 11  Hypertension      4537 non-null   float64
 12  Alcohol           70000 non-null  float64
 13  PhysicalActivity  70000 non-null  float64
 14  HeartRate         4237 non-null   float64
 15  Platelets         299 non-null    float64
 16  SerumCreatinine   299 non-null    float64
 17  SerumSodium       299 non-null    float64
 18  CPK               299 non-null    float64
 19  Target            74537 non-null  int64
dtypes: float64(18), int64(2)
memory usage: 11.4 MB
None
Age                     0
Sex                     0
Height               4537
Weight               4537
BMI                 70318
SystolicBP            299
DiastolicBP           299
TotalCholesterol      349
Glucose               687
Smoking               299
Diabetes            70000
Hypertension        70000
Alcohol              4537
PhysicalActivity     4537
HeartRate           70300
Platelets           74238
SerumCreatinine     74238
SerumSodium         74238
CPK                 74238
Target                  0
dtype: int64

In [110]:
import pandas as pd

df = pd.read_csv(
    "datasets/combined_kidney_dataset.csv",
    low_memory=False
)

print(df.info())

print(df.isnull().sum())

print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 21058 entries, 0 to 21057
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          507 non-null    float64
 1   BloodPressure                505 non-null    float64
 2   SpecificGravity              462 non-null    float64
 3   Albumin                      463 non-null    float64
 4   Sugar                        460 non-null    float64
 5   BloodGlucose                 465 non-null    float64
 6   BloodUrea                    496 non-null    float64
 7   SerumCreatinine              498 non-null    float64
 8   Sodium                       413 non-null    float64
 9   Potassium                    412 non-null    float64
 10  Hemoglobin                   455 non-null    float64
 11  PackedCellVolume             431 non-null    str
 12  WBC                          387 non-null    str
 13  RBC                          353 non-null    str
 14  Hypertension                 517 non-null    str
 15  Diabetes                     517 non-null    str
 16  CoronaryArteryDisease        517 non-null    str
 17  Appetite                     518 non-null    str
 18  PedalEdema                   518 non-null    str
 19  Anemia                       518 non-null    str
 20  eGFR                         0 non-null      float64
 21  UrineProteinCreatinineRatio  0 non-null      float64
 22  UrineOutput                  0 non-null      float64
 23  SerumAlbumin                 0 non-null      float64
 24  Calcium                      0 non-null      float64
 25  Phosphate                    0 non-null      float64
 26  BMI                          0 non-null      float64
 27  Smoking                      0 non-null      float64
 28  PhysicalActivity             0 non-null      float64
 29  CystatinC                    0 non-null      float64
 30  Target                       20938 non-null  str
dtypes: float64(21), str(10)
memory usage: 5.0 MB
None
Age                            20551
BloodPressure                  20553
SpecificGravity                20596
Albumin                        20595
Sugar                          20598
BloodGlucose                   20593
BloodUrea                      20562
SerumCreatinine                20560
Sodium                         20645
Potassium                      20646
Hemoglobin                     20603
PackedCellVolume               20627
WBC                            20671
RBC                            20705
Hypertension                   20541
Diabetes                       20541
CoronaryArteryDisease          20541
Appetite                       20540
PedalEdema                     20540
Anemia                         20540
eGFR                           21058
UrineProteinCreatinineRatio    21058
UrineOutput                    21058
SerumAlbumin                   21058
Calcium                        21058
Phosphate                      21058
BMI                            21058
Smoking                        21058
PhysicalActivity               21058
CystatinC                      21058
Target                           120
dtype: int64
    Age  BloodPressure  SpecificGravity  Albumin  Sugar  BloodGlucose  \
0  48.0           80.0            1.020      1.0    0.0         121.0
1   7.0           50.0            1.020      4.0    0.0           NaN
2  62.0           80.0            1.010      2.0    3.0         423.0
3  48.0           70.0            1.005      4.0    0.0         117.0
4  51.0           80.0            1.010      2.0    0.0         106.0

   BloodUrea  SerumCreatinine  Sodium  Potassium  ...  \
0       36.0              1.2     NaN        NaN  ...
1       18.0              0.8     NaN        NaN  ...
2       53.0              1.8     NaN        NaN  ...
3       56.0              3.8   111.0        2.5  ...
4       26.0              1.4     NaN        NaN  ...

   UrineProteinCreatinineRatio UrineOutput SerumAlbumin Calcium Phosphate BMI  \
0                          NaN         NaN          NaN     NaN       NaN NaN
1                          NaN         NaN          NaN     NaN       NaN NaN
2                          NaN         NaN          NaN     NaN       NaN NaN
3                          NaN         NaN          NaN     NaN       NaN NaN
4                          NaN         NaN          NaN     NaN       NaN NaN

  Smoking PhysicalActivity CystatinC Target
0     NaN              NaN       NaN    ckd
1     NaN              NaN       NaN    ckd
2     NaN              NaN       NaN    ckd
3     NaN              NaN       NaN    ckd
4     NaN              NaN       NaN    ckd

[5 rows x 31 columns]

In [111]:
import pandas as pd

df = pd.read_csv("datasets/kidney_disease_dataset1.csv")

print(df.columns.tolist())

print()

print(df.head())

['Age of the patient', 'Blood pressure (mm/Hg)', 'Specific gravity of urine', 'Albumin in urine', 'Sugar in urine', 'Red blood cells in urine', 'Pus cells in urine', 'Pus cell clumps in urine', 'Bacteria in urine', 'Random blood glucose level (mg/dl)', 'Blood urea (mg/dl)', 'Serum creatinine (mg/dl)', 'Sodium level (mEq/L)', 'Potassium level (mEq/L)', 'Hemoglobin level (gms)', 'Packed cell volume (%)', 'White blood cell count (cells/cumm)', 'Red blood cell count (millions/cumm)', 'Hypertension (yes/no)', 'Diabetes mellitus (yes/no)', 'Coronary artery disease (yes/no)', 'Appetite (good/poor)', 'Pedal edema (yes/no)', 'Anemia (yes/no)', 'Estimated Glomerular Filtration Rate (eGFR)', 'Urine protein-to-creatinine ratio', 'Urine output (ml/day)', 'Serum albumin level', 'Cholesterol level', 'Parathyroid hormone (PTH) level', 'Serum calcium level', 'Serum phosphate level', 'Family history of chronic kidney disease', 'Smoking status', 'Body Mass Index (BMI)', 'Physical activity level', 'Duration of diabetes mellitus (years)', 'Duration of hypertension (years)', 'Cystatin C level', 'Urinary sediment microscopy results', 'C-reactive protein (CRP) level', 'Interleukin-6 (IL-6) level', 'Target']

   Age of the patient  Blood pressure (mm/Hg)  Specific gravity of urine  \
0                  54                     167                      1.023
1                  42                     127                      1.023
2                  38                     148                      1.016
3                   7                      98                      1.017
4                  67                     174                      1.015

   Albumin in urine  Sugar in urine Red blood cells in urine  \
0                 1               4                   normal
1                 3               2                   normal
2                 0               0                 abnormal
3                 4               0                 abnormal
4                 1               1                   normal

  Pus cells in urine Pus cell clumps in urine Bacteria in urine  \
0           abnormal              not present       not present
1             normal              not present           present
2             normal              not present       not present
3             normal              not present           present
4           abnormal              not present       not present

   Random blood glucose level (mg/dl)  ...  Smoking status  \
0                                  96  ...             yes
1                                  73  ...              no
2                                  77  ...              no
3                                 225  ...              no
4                                 376  ...             yes

   Body Mass Index (BMI)  Physical activity level  \
0                   25.3                      low
1                   20.6                 moderate
2                   38.4                     high
3                   24.7                     high
4                   17.6                     high

   Duration of diabetes mellitus (years)  Duration of hypertension (years)  \
0                                      4                                16
1                                      3                                13
2                                     11                                23
3                                     24                                 3
4                                     22                                24

   Cystatin C level  Urinary sediment microscopy results  \
0              0.67                               normal
1              0.55                             abnormal
2              2.37                             abnormal
3              2.54                             abnormal
4              1.90                               normal

   C-reactive protein (CRP) level Interleukin-6 (IL-6) level      Target
0                            4.88                      10.23  No_Disease
1                            4.49                      13.11    Low_Risk
2                            4.57                      13.27  No_Disease
3                            8.57                      12.36  No_Disease
4                            6.75                       1.46  No_Disease

[5 rows x 43 columns]

In [112]:
import pandas as pd

df = pd.read_csv("datasets/combined_kidney_dataset.csv")

print(df.info())

print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 21058 entries, 0 to 21057
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          21045 non-null  float64
 1   BloodPressure                21043 non-null  float64
 2   SpecificGravity              21000 non-null  float64
 3   Albumin                      21001 non-null  float64
 4   Sugar                        20998 non-null  float64
 5   BloodGlucose                 21003 non-null  float64
 6   BloodUrea                    21034 non-null  float64
 7   SerumCreatinine              21036 non-null  float64
 8   Sodium                       20951 non-null  float64
 9   Potassium                    20950 non-null  float64
 10  Hemoglobin                   20993 non-null  float64
 11  PackedCellVolume             20969 non-null  str
 12  WBC                          20925 non-null  str
 13  RBC                          20891 non-null  str
 14  Hypertension                 21055 non-null  str
 15  Diabetes                     21055 non-null  str
 16  CoronaryArteryDisease        21055 non-null  str
 17  Appetite                     21056 non-null  str
 18  PedalEdema                   21056 non-null  str
 19  Anemia                       21056 non-null  str
 20  eGFR                         20538 non-null  float64
 21  UrineProteinCreatinineRatio  20538 non-null  float64
 22  UrineOutput                  20538 non-null  float64
 23  SerumAlbumin                 20538 non-null  float64
 24  Calcium                      20538 non-null  float64
 25  Phosphate                    20538 non-null  float64
 26  BMI                          20538 non-null  float64
 27  Smoking                      20538 non-null  str
 28  PhysicalActivity             20538 non-null  str
 29  CystatinC                    20538 non-null  float64
 30  Target                       20938 non-null  str
dtypes: float64(19), str(12)
memory usage: 5.0 MB
None
Age                             13
BloodPressure                   15
SpecificGravity                 58
Albumin                         57
Sugar                           60
BloodGlucose                    55
BloodUrea                       24
SerumCreatinine                 22
Sodium                         107
Potassium                      108
Hemoglobin                      65
PackedCellVolume                89
WBC                            133
RBC                            167
Hypertension                     3
Diabetes                         3
CoronaryArteryDisease            3
Appetite                         2
PedalEdema                       2
Anemia                           2
eGFR                           520
UrineProteinCreatinineRatio    520
UrineOutput                    520
SerumAlbumin                   520
Calcium                        520
Phosphate                      520
BMI                            520
Smoking                        520
PhysicalActivity               520
CystatinC                      520
Target                         120
dtype: int64

In [113]:
import pandas as pd

df = pd.read_csv("datasets/clean_diabetes_dataset.csv")
print(df.columns.tolist())

['Age', 'Gender', 'Pregnancies', 'Glucose', 'HbA1c', 'BMI', 'BloodPressure', 'Insulin', 'Hypertension', 'Smoking', 'FamilyHistory', 'HeartDisease', 'Outcome']

In [114]:
import pandas as pd

df = pd.read_csv("datasets/clean_heart_dataset.csv")
print(df.columns.tolist())

['Age', 'Sex', 'Height', 'Weight', 'BMI', 'SystolicBP', 'DiastolicBP', 'TotalCholesterol', 'Glucose', 'Smoking', 'Diabetes', 'Hypertension', 'Alcohol', 'PhysicalActivity', 'HeartRate', 'Platelets', 'SerumCreatinine', 'SerumSodium', 'CPK', 'Target']

In [115]:
import pandas as pd

df = pd.read_csv("datasets/clean_kidney_dataset.csv")
print(df.columns.tolist())

['Age', 'BloodPressure', 'SpecificGravity', 'Albumin', 'Sugar', 'BloodGlucose', 'BloodUrea', 'SerumCreatinine', 'Sodium', 'Potassium', 'Hemoglobin', 'PackedCellVolume', 'WBC', 'RBC', 'Hypertension', 'Diabetes', 'CoronaryArteryDisease', 'Appetite', 'PedalEdema', 'Anemia', 'eGFR', 'UrineProteinCreatinineRatio', 'UrineOutput', 'SerumAlbumin', 'Calcium', 'Phosphate', 'BMI', 'Smoking', 'PhysicalActivity', 'CystatinC', 'Target']